#!/bin/bash

# Actually want to "git fetch -a && git reset --hard origin/master"
# but this will prevent us from blowing away any local edits someone makes

ssh fffffat@fffff.at "cd ~/gold.fffff.at; git pull origin master"
